# Shows the "Sponsor" button on the repo. Uncomment/add platforms as they
# are set up.
github: [sutantodadang]
# ko_fi: sutantodadang
# open_collective: luncur
# custom: ["https://saweria.co/sutantodadang"]
