package server

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/sutantodadang/luncur/internal/store"
)

// webhookMaxBody caps a hook request body: a push payload larger than 1 MiB
// is a mistake, not a webhook.
const webhookMaxBody = 1 << 20

// errNotGitApp is enableWebhook's sentinel for "this app has no git source
// to build from". Callers map it to 400 bad_request.
var errNotGitApp = errors.New("webhooks require a git-source app")

// webhookPath returns the public (unauthenticated) hook URL path a provider
// posts pushes to.
func webhookPath(project, app string) string {
	return "/hooks/apps/" + project + "/" + app
}

// enableWebhook is the shared core of handleWebhookEnable: generate a fresh
// 32-byte secret (hex-encoded, 64 chars — this is what providers sign/
// compare with), seal it, and store it. Always regenerates: re-enabling an
// already-enabled webhook rotates the secret, invalidating the old one.
// Returns the plaintext hex secret — the ONLY time it is ever available in
// plaintext; only the sealed form persists.
func (s *server) enableWebhook(a store.App) (string, error) {
	if a.SourceType != "git" {
		return "", errNotGitApp
	}
	if s.sealer == nil {
		return "", errSealerUnavailable
	}
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	secretHex := hex.EncodeToString(raw)
	sealed, err := s.sealer.Seal([]byte(secretHex))
	if err != nil {
		return "", err
	}
	if err := s.st.SetWebhookSecret(a.ID, sealed); err != nil {
		return "", err
	}
	return secretHex, nil
}

// handleWebhookEnable turns on (or rotates) an app's deploy webhook. The
// secret is returned in this response ONLY — it is never recoverable from
// the store afterward (only the sealed bytes persist).
func (s *server) handleWebhookEnable(w http.ResponseWriter, r *http.Request, u store.User) {
	p, ok := s.requireProject(w, u, r.PathValue("project"))
	if !ok {
		return
	}
	a, ok := s.requireApp(w, p, r.PathValue("app"))
	if !ok {
		return
	}
	if a.Ejected {
		writeError(w, http.StatusConflict, "app_ejected", errAppEjected.Error())
		return
	}

	secretHex, err := s.enableWebhook(a)
	if err != nil {
		switch {
		case errors.Is(err, errNotGitApp):
			writeError(w, http.StatusBadRequest, "bad_request", errNotGitApp.Error())
		case errors.Is(err, errSealerUnavailable):
			writeError(w, http.StatusServiceUnavailable, "sealer_unavailable", errSealerUnavailable.Error())
		default:
			log.Printf("enable webhook: %v", err)
			writeError(w, http.StatusInternalServerError, "internal", "internal error")
		}
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"enabled": true, "path": webhookPath(p.Name, a.Name), "secret": secretHex,
	})
}

// handleWebhookDisable turns off an app's deploy webhook: the stored
// secret is cleared, so any previously-issued secret stops verifying.
func (s *server) handleWebhookDisable(w http.ResponseWriter, r *http.Request, u store.User) {
	p, ok := s.requireProject(w, u, r.PathValue("project"))
	if !ok {
		return
	}
	a, ok := s.requireApp(w, p, r.PathValue("app"))
	if !ok {
		return
	}
	if a.Ejected {
		writeError(w, http.StatusConflict, "app_ejected", errAppEjected.Error())
		return
	}
	if err := s.st.SetWebhookSecret(a.ID, nil); err != nil {
		log.Printf("disable webhook: %v", err)
		writeError(w, http.StatusInternalServerError, "internal", "internal error")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"enabled": false})
}

// handleWebhookShow reports whether an app's webhook is enabled and, if so,
// its path (never its secret — that's only ever returned by enable).
func (s *server) handleWebhookShow(w http.ResponseWriter, r *http.Request, u store.User) {
	p, ok := s.requireProject(w, u, r.PathValue("project"))
	if !ok {
		return
	}
	a, ok := s.requireApp(w, p, r.PathValue("app"))
	if !ok {
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"enabled": a.WebhookSecret != nil, "path": webhookPath(p.Name, a.Name),
	})
}

// verifyWebhook checks a hook request's signature against secret (the
// plaintext hex string generated by enableWebhook), covering both provider
// schemes: GitHub/Gitea's HMAC-SHA256 "X-Hub-Signature-256: sha256=<hex>"
// over the raw body, or GitLab's plain "X-Gitlab-Token: <secret>". Returns
// false when neither header is present, or the one present doesn't match —
// callers must answer every false alike (identical 401, no existence
// oracle).
func verifyWebhook(r *http.Request, body []byte, secret string) bool {
	if sig := r.Header.Get("X-Hub-Signature-256"); sig != "" {
		const prefix = "sha256="
		if !strings.HasPrefix(sig, prefix) {
			return false
		}
		want, err := hex.DecodeString(strings.TrimPrefix(sig, prefix))
		if err != nil {
			return false
		}
		mac := hmac.New(sha256.New, []byte(secret))
		mac.Write(body)
		return hmac.Equal(mac.Sum(nil), want)
	}
	if tok := r.Header.Get("X-Gitlab-Token"); tok != "" {
		return subtle.ConstantTimeCompare([]byte(tok), []byte(secret)) == 1
	}
	return false
}

// webhookUnauthorized writes the one identical 401 body every auth failure
// answers with — unknown project/app, disabled webhook, unseal failure, or
// bad signature all look the same to the caller, so a hook URL can't be
// used to probe for an app's existence.
func webhookUnauthorized(w http.ResponseWriter) {
	writeError(w, http.StatusUnauthorized, "unauthorized", "unauthorized")
}

// handleWebhookTrigger is the public (unauthenticated at the HTTP-auth
// layer) endpoint a git provider posts pushes to. Auth is the HMAC/token
// check itself: every failure up to and including a bad signature answers
// with the identical 401 body. Only after that does event/branch/ejected/
// dedupe logic run, matching the shared deployGitApp core used by the API
// and UI deploy paths.
func (s *server) handleWebhookTrigger(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, webhookMaxBody)
	body, err := io.ReadAll(r.Body)
	if err != nil {
		webhookUnauthorized(w)
		return
	}

	p, err := s.st.GetProject(r.PathValue("project"))
	if err != nil {
		webhookUnauthorized(w)
		return
	}
	a, err := s.st.GetApp(p.ID, r.PathValue("app"))
	if err != nil {
		webhookUnauthorized(w)
		return
	}
	if a.WebhookSecret == nil || s.sealer == nil {
		webhookUnauthorized(w)
		return
	}
	plain, err := s.sealer.Open(a.WebhookSecret)
	if err != nil {
		webhookUnauthorized(w)
		return
	}
	if !verifyWebhook(r, body, string(plain)) {
		webhookUnauthorized(w)
		return
	}

	if info := auditFrom(r.Context()); info != nil {
		info.Email = "webhook"
		info.Pattern = r.Pattern
	}

	// Authenticated from here on — failures are ordinary status codes.
	if r.Header.Get("X-GitHub-Event") == "ping" {
		writeJSON(w, http.StatusOK, map[string]any{"pong": true})
		return
	}

	var payload struct {
		Ref        string `json:"ref"`
		ObjectKind string `json:"object_kind"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid JSON body")
		return
	}
	if payload.ObjectKind != "" && payload.ObjectKind != "push" {
		writeJSON(w, http.StatusOK, map[string]any{"skipped": "event"})
		return
	}

	branch := a.GitBranch
	if branch == "" {
		branch = "main"
	}
	if payload.Ref != "refs/heads/"+branch {
		writeJSON(w, http.StatusOK, map[string]any{"skipped": "branch"})
		return
	}

	if a.Ejected {
		writeError(w, http.StatusConflict, "app_ejected", errAppEjected.Error())
		return
	}

	if latest, err := s.st.LatestDeployment(a.ID); err == nil {
		if latest.Status == "building" {
			writeJSON(w, http.StatusAccepted, map[string]any{
				"deployment_id": latest.ID, "skipped": "in_progress",
			})
			return
		}
	} else if !errors.Is(err, store.ErrNotFound) {
		log.Printf("webhook latest deployment: %v", err)
		writeError(w, http.StatusInternalServerError, "internal", "internal error")
		return
	}

	d, err := s.deployGitApp(p, a, 0)
	if err != nil {
		switch {
		case errors.Is(err, errKubeUnavailable):
			writeError(w, http.StatusServiceUnavailable, "kubernetes_unavailable", "kubernetes is not configured")
		case errors.Is(err, errBuildUnavailable):
			writeError(w, http.StatusServiceUnavailable, "build_unavailable", "server has no data directory configured")
		default:
			log.Printf("webhook deploy: %v", err)
			writeError(w, http.StatusInternalServerError, "internal", "internal error")
		}
		return
	}
	writeJSON(w, http.StatusAccepted, map[string]any{"deployment_id": d.ID})
}
